### ISSUE TITLE
Error Importing Darts Models in TFB Benchmark: AttributeError for 'RNNModel' and ImportError for 'LightGBMModel'

### ISSUE THREAD

**Issue by Realsumen** [decisionintelligence/TFB#8]
**Description:**
I am encountering issues while running the TFB benchmark scripts where certain Darts models fail to import. The specific errors are AttributeError for RNNModel and ImportError for LightGBMModel.

**Environment:**

Operating System: Windows
Python Version: 3.8 (Anaconda environment)
Darts Version:  0.25.0

**Error Logs:**

2024-05-21 15:56:35 [INFO] ts_benchmark.data.data_source(95): Start loading 1 series in parallel
2024-05-21 15:56:35 [INFO] ts_benchmark.data.data_source(104): Data loading finished.
2024-05-21 15:56:35 [INFO] ts_benchmark.data.suites.global_storage(40): Data server starting...
2024-05-21 15:56:35 [INFO] ts_benchmark.data.suites.global_storage(41): Start sending data to the global storage.
2024-05-21 15:56:35 [INFO] ts_benchmark.data.suites.global_storage(46): Notifying all workers to sync data from the global storage.
2024-05-21 15:56:35 [INFO] ts_benchmark.data.suites.global_storage(49): Data server started.
2024-05-21 15:56:36 [WARNING] darts.models.utils(19): The `LightGBM` module could not be imported. To enable LightGBM support in Darts, follow the detailed instructions in the installation guide: https://github.com/unit8co/darts/blob/master/INSTALL.md
2024-05-21 15:56:36 [WARNING] darts.models.utils(19): The `Prophet` module could not be imported. To enable Prophet support in Darts, follow the detailed instructions in the installation guide: https://github.com/unit8co/darts/blob/master/INSTALL.md
2024-05-21 15:56:36 [WARNING] darts.models.utils(19): The `CatBoost` module could not be imported. To enable CatBoost support in Darts, follow the detailed instructions in the installation guide: https://github.com/unit8co/darts/blob/master/INSTALL.md
2024-05-21 15:56:37 [WARNING] ts_benchmark.baselines.darts.darts_models(327): Model CatBoostModel is not available, skipping model registration
2024-05-21 15:56:37 [WARNING] ts_benchmark.baselines.darts.darts_models(327): Model LightGBMModel is not available, skipping model registration
Traceback (most recent call last):
  File "C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\models\get_model.py", line 39, in get_model_info
    model_info = import_model_info(model_class)
  File "C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\models\get_model.py", line 33, in import_model_info
    model_info = getattr(mod, class_name)
AttributeError: module 'darts' has no attribute 'RNNModel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/run_benchmark.py", line 295, in <module>
    log_filenames = pipeline(
  File "C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\pipeline.py", line 105, in pipeline
    model_factory_list = get_model(model_config)
  File "C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\models\get_model.py", line 127, in get_model
    model_info = get_model_info(model_config)  # Obtain model information
  File "C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\models\get_model.py", line 45, in get_model_info
    model_info = import_model_info(model_class)
  File "C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\models\get_model.py", line 31, in import_model_info
    mod = importlib.import_module(model_package)
  File "C:\Users\jrfundoffice02\anaconda3\envs\tfb-env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\baselines\darts\__init__.py", line 56, in <module>
    from ts_benchmark.baselines.darts.darts_models import LightGBMModel
ImportError: cannot import name 'LightGBMModel' from 'ts_benchmark.baselines.darts.darts_models' (C:\Users\jrfundoffice02\workspace\TFB\ts_benchmark\baselines\darts\darts_models.py)

**Steps to Reproduce**

run "sh ./scripts/multivariate_forecast/ILI_script/RNN.sh"

**Comment by qiu69** [comment]
Thank you for your attention and questions. We apologize for any inconvenience caused by our continuous code updates. You are currently using old code. Please use the latest code as it may solve the problem you are experiencing.

**Comment by Realsumen** [comment]
Hi, it appears that the `RNNModel` attribute is missing from the Darts library, even though I am using the latest version of the code. Are there any potential mistakes in the ./scripts/multivariate_forecast/ILI_script/RNN.sh? I thought the module name should be darts.models.RNNModel.

**Comment by qiu69** [comment]
Could you show me your "pip list", and the error log?

**Comment by Realsumen** [comment]
resolved

**Comment by codeman6688** [comment]
I have encountered the same problem. Can you share some solutions

**Comment by qiu69** [comment]
Thank you for your attention and questions. Please ensure that you are using the latest code and that the darts version is 0.25.0.

**Comment by qiu69** [comment]
@codeman6688 Have you solved the problem？

**Comment by codeman6688** [comment]
@qiu69 Sorry for the late reply, the problem has been solved

**Comment by qiu69** [comment]
> I have encountered the same problem. Can you share some solutions
 May I ask how you solved the problem

**Comment by qiu69** [comment]
@codeman6688 May I ask how you solved the problem

**Comment by qiu69** [comment]
@Realsumen  May I ask how you solved the problem

**Comment by Realsumen** [comment]
Hi, sorry for the late response. A try statement is actually catching this error. Another error, caused by the missing dependency LightGBM, is making it visible in the output.

**Comment by qiu69** [comment]
@Realsumen  Thank you for your response!
